### ISSUE TITLE
    "target"  :   "ESNext" ，    onready装饰器不能正常使用。

### ISSUE THREAD

**Issue by scgm0** [Geequlim/ECMAScript#118]
ts：
![image](https://user-images.githubusercontent.com/52148221/156973321-f72174e0-dff5-4d86-b209-b2443bbdc9db.png)
ESNext：
![image](https://user-images.githubusercontent.com/52148221/156973386-b1d9fcd9-9caa-4c53-ba3a-4a8c5bbe22fb.png)
ES2021 & ES2020：
![image](https://user-images.githubusercontent.com/52148221/156973464-9430e23b-9d35-44ff-a2ac-73ff29311971.png)

ts装饰器不能将已定义的普通属性更改为 setter getter ，而 ESNext 的装饰器是修改原属性，ES2021 && ES2020 则是额外添加。

所以要使用onready装饰器，要么 target 改成 ES2021 || ES2020，要么原属性本身就是 setter getter。

希望默认生成的tsconfig.json的 target 改为 ES2021 || ES2020，我今天才发现怎么解决onready装饰器不能正常使用。。。

网络问题还重写了一次文，悲(

话说，大佬什么时候更新啊（笑）

**Comment by citizenll** [comment]
Bro what you need is 
>tsconfig.json
```json
"useDefineForClassFields":false
```
Here is a starting [`template`](https://github.com/citizenll/godot-typescript-starter)

**Comment by scgm0** [comment]
> 兄弟你需要的是
> 
> > tsconfig.json
> 
> ```json
> "useDefineForClassFields":false
> ```
> 
> 这是一个起始[`模板`](https://github.com/citizenll/godot-typescript-starter)

噢，谢谢，我有解决的办法，但我更希望官方生成的模板能支持一下，毕竟也不是什么难事。
