### ISSUE TITLE
Can't import a library that doesn't have a class definition

### ISSUE THREAD

**Issue by xxmatxx** [Geequlim/ECMAScript#120]
I can't import a library that doesn't have a class definition. All import ends with: 

```
ERROR: get_instance_base_type: Parameter "ecma_class" is null.
   At: modules/ECMAScript/ecmascript.cpp:29
```
Library i tried:
https://csv.js.org/
https://www.papaparse.com/

**Comment by nmerget** [comment]
[Here](https://github.com/nmerget/gott/blob/main/src/papaparseTest.tsx) is a working example.

I use TS here and compile all `npm_modules` I use to a script which will be built by `esbuild`. Besides this, you could use https://unpkg.com/papaparse@5.4.1/papaparse.min.js which should be the same like the `esbuild` file.

**Comment by nmerget** [comment]
Added this question to [gotchas](https://geequlim.github.io/ECMAScript/gotchas/#import-dependency-from-node_modules)
