### ISSUE TITLE
Not an issue but a general question

### ISSUE THREAD

**Issue by anatoli-dp** [Geequlim/ECMAScript#123]
As it is i much prefer javascript over gdscript however would like to get one thing sorted before trying out this package . . . what happens if i use a custom module? I am currenty using zylan voxel module in my game and want to be able to program in javascript but am unsure if the api would also be available or is it strictly the api that godot comes with natively? Does this project use some sort of reflection allowing different modules to still be used and called upon or is this a nogo for that?

**Comment by nmerget** [comment]
I didn't test the voxel module, but in general, it is possible to use GDScript and JS/TS.

I have an example with a [GDScript](https://github.com/nmerget/gott/blob/main/scripts/gd/Bla.gd) and [TS](https://github.com/nmerget/gott/blob/main/src/test.tsx) file. 

The important thing would be that you use `new()` to instantiate and `call` to execute the function:

````
import Bla from "res://scripts/gd/Bla.gd";
...
const bla: Bla = Bla.new();
bla.call("run_in_bla");
````

Another way would be to use a signal with some "connection" GDScript or you can try it with a auto-load sigleton

**Comment by nmerget** [comment]
Added an example: https://geequlim.github.io/ECMAScript/examples/use-gdscript-in-ts/
