### ISSUE TITLE
3.5-stable compiles and runs trivial test app

### ISSUE THREAD

**Issue by bumblemeow** [Geequlim/ECMAScript#130]
I just thought I would let people know that 3.5-stable compiles and at least runs a 'hello TypeScript' example I made. Not at all an extensive test suite by any means but at least it's not a failure right away. I will be interested in seeing if others are having success with their more substantial projects.

**Comment by nmerget** [comment]
We have a section for tutorials and demos in the [readme](https://github.com/Geequlim/ECMAScript#documentation-tutorials--demos). 

Feel free to open a PR with a link to your example if you want to share it 👍 

I gonna close this issue for now.
