### ISSUE TITLE
Upgrade to a newer quickjs

### ISSUE THREAD

**Issue by fire** [Geequlim/ECMAScript#137]
Upgrade to https://github.com/bellard/quickjs version 2788d71 on Mar 6

**Comment by Geequlim** [comment]
These are some required modification to QuickJS to support binding to godot.
And the debugger code is mostly from https://github.com/koush/vscode-quickjs-debug.

We'd better finish the godot binding first. For future version quickjs we can add patches to the build script.

**Comment by fire** [comment]
The bindings are finished but I had to modify the quick js code.

**Comment by fire** [comment]
Closing after merge https://github.com/Geequlim/ECMAScript/commit/9a3cd3fe74ebb2dcc26ad496c55a8ae3db9cfe4b
