### ISSUE TITLE
Thoughts and comments on moving quickjs to a thirdparty directory?

### ISSUE THREAD

**Issue by fire** [Geequlim/ECMAScript#139]
Thoughts and comments on moving quickjs to a thirdparty directory?

I did in my branch but wanted commentary.

**Comment by Geequlim** [comment]
Do you mean the thirdparty folder of godot?
I don't think it's a good idea. It's simpler to simple clone the repo to godot modules folder and build it for other developers.

**Comment by Geequlim** [comment]
This module should contains all the dependencies. In V8 or nodejs backend the static libraries will be included instead of build from code with scons.

**Comment by fire** [comment]
you misunderstood.

1. javascript/quickjs/quickjs -> javascript/thirdparty/quickjs

**Comment by fire** [comment]
For example:

1. javascript/thirdparty/quickjs
2. javascript/thirdparty/v8
3. javascript/thirdparty/wasm3

**Comment by Geequlim** [comment]
That's looks good to me

**Comment by fire** [comment]
My pr here https://github.com/Geequlim/ECMAScript/pull/156 moves the quickjs folder to thirdparty.

**Comment by fire** [comment]
Closing after merge. https://github.com/Geequlim/ECMAScript/commit/9a3cd3fe74ebb2dcc26ad496c55a8ae3db9cfe4b
