### ISSUE TITLE
Support scons custom_modules

### ISSUE THREAD

**Issue by fire** [Geequlim/ECMAScript#140]
custom_modules is used a lot in my build system, I had to inline two python files to restore this and it made my code style worse.

Currently the SCons is told the location of the builtin_api.gen.json is custom_modules/builtin_api.gen.json I don't remember the exact error.

**Comment by Geequlim** [comment]
Never head of custom_nodule any documentation about this?

**Comment by fire** [comment]
https://docs.godotengine.org/en/stable/development/compiling/introduction_to_the_buildsystem.html#custom-modules

**Comment by fire** [comment]
I use git subrepo to merge so not necessary.
