### ISSUE TITLE
[Typescript] Generated declaration file expands INF and NAN incorrectly

### ISSUE THREAD

**Issue by DenisBelmondo** [Geequlim/ECMAScript#15]
Hello there, there seems to be an issue according to Typescript's compiler, tsc, with the following lines in the automatically-generated godot.d.ts:

![image](https://user-images.githubusercontent.com/8296741/78412746-beec6700-75d1-11ea-9e03-f4eb655f4e7f.png)

This yields the following errors:

```
../godot.d.ts:2177:15 - error TS1005: ',' expected.

2177  const INF: 1.#INF;
                   ~~~~

../godot.d.ts:2182:15 - error TS1005: ',' expected.

2182  const NAN: 1.#QNAN;
```

Thankfully, the typescript file for my compiles just fine regardless.

**Steps to reproduce:**

1. Create a new Godot project
2. Select `Project > Tools > ECMAScript > Generate Typescript Declaration File` which generates `godot.d.ts` in `res://`
3. Create a new Typescript file anywhere. In my case, it's `res://src/ts/new_script.ts`
4. In `res://src/ts/`, create a subdirectory called `godot` and place `godot.d.ts` in it.
5. At the top of `new_script.ts`, import the declarations by writing `import "godot";`
6. Run `tsc` in the `src/ts/` directory. It will then print the errors.

**Comment by Geequlim** [comment]
I can't reproduce this problem.
You'd better using latest code to compile.
