### ISSUE TITLE
Make javascript module for Godot Engine 4 production ready

### ISSUE THREAD

**Issue by fire** [Geequlim/ECMAScript#151]
List of issues to create pull requests.

- [x] formatting in c++
- [x] formatting in python
- [x] warnings as errors is failing 
- [x] cicd is failing https://github.com/V-Sekai/godot/actions/runs/4779661841/jobs/8496916452
- [x] Complete https://github.com/V-Sekai/godot/commits/javascript
- [x] Resource api changed
- [x] Error: modules/javascript/thirdparty/quickjs/./quickjs/quickjs.h:949:49: error: cast between incompatible function types from 'JSValue (*)(JSContext*, JSValue, int, JSValue*, int)' to 'JSValue (*)(JSContext*, JSValue, int, JSValue*)' [-Werror=cast-function-type]
  949 |     return JS_NewCFunction2(ctx, (JSCFunction *)func, name, length, cproto, magic);
- [x] modules/javascript/thirdparty/quickjs/quickjs/cutils.c:179:13: error: comparison of integers of different signs: 'int' and 'unsigned int' [-Werror,-Wsign-compare]
    if (len < sizeof(buf)) {
        ~~~ ^ ~~~~~~~~~~~
modules/javascript/thirdparty/quickjs/quickjs/cutils.c:300:11: error: comparison of integers of different signs: 'int' and 'const unsigned int' [-Werror,-Wsign-compare]
    if (c < utf8_min_code[l - 1])

**Comment by fire** [comment]
@Geequlim Can I help contribute / maintain the project?

**Comment by Geequlim** [comment]
@fire Of course you can. 

This project is something I've always wanted to do well but couldn't find enough time to actually finish it.

If you need any help I will do my best to answer it for you.

**Comment by fire** [comment]
I want to merge prs.

**Comment by lh472266503** [comment]
What's the current status of the development progress?
I want to learn and dev.

**Comment by fire** [comment]
@Geequlim and I have been busy. I honestly forgot about this.

I want to get javascript on godot 4.1

**Comment by fire** [comment]
The branch needs an update but I can do a console log from js.

**Comment by fire** [comment]
Completed after the merge.
