### ISSUE TITLE
Merge gd4 branch to master

### ISSUE THREAD

**Issue by fire** [Geequlim/ECMAScript#152]
@Geequlim 

What do you think about?

1. Branch master to be godot3
1. Merging gd4 to master?

**Comment by why-try313** [comment]
@fire Some things to note:
- The project isn't what we could call "stable", setting it as master might not be the better choice
- The guys from the main repo move _fast_, master is now Godot 4.1 (dev) and could lead to confusion

But overall, at some point it would be great to have Godot 4.0rc Javascript module as master indeed

**Comment by fire** [comment]
I'll check back later when Godot Engine 4.0 / Javascript module is considered more stable.
