### ISSUE TITLE
CommonJS Module Support

### ISSUE THREAD

**Issue by animanmaster** [Geequlim/ECMAScript#155]
The README seems to indicate that `require`-ing modules works, but when I tried to import a JS file that uses `require()`, I get a `'require' is not defined` error message. Is the README incorrect, or is there a way to make JS files that use `require` work?

**Comment by GTNT-Github** [comment]
I'm having the same issue, any info?

**Comment by sr229** [comment]
Most likely missing the CommonJS module resolution in the engine.

**Comment by nmerget** [comment]
> The README seems to indicate that `require`-ing modules work, but when I tried to import a JS file that uses `require()`, I got a `'require' is not defined` error message. Is the README incorrect, or is there a way to make JS files that use `require` work?

I think the documentation is incorrect. I couldn't find any hint in [QuickJS](https://bellard.org/quickjs/quickjs.html) about it. 
I also tested this [workaround](https://dev.to/caspergeek/how-to-use-require-in-ecmascript-modules-1l42), but it leads to an error in QuickJS that the module is `__null`. 
There could be another issue when you want to use a nodeJS module like `crypto`: I think it is not implemented in QuickJS, so you need to get another package from npm that simulates the same logic. 

Maybe https://github.com/IvanGaravito/quickjs-require could be something (it was the first repo I found)?

Besides this, a lot of CommonJS Modules can be used in ECMAScript or in Typescript with `npm install --save-dev @types/xxx`. Can you provide the module you used which didn't work as expected?

**Comment by Geequlim** [comment]
CommonJS is removed.
We recommend using a packager such as Webpack to solve the use of npm libraries
