### ISSUE TITLE
dev is ok , when i build get error below

### ISSUE THREAD

**Issue by analysisi** [Geequlim/ECMAScript#163]
import { ColorPicker } from "vue3-colorpicker";
         ^^^^^^^^^^^
SyntaxError: Named export 'ColorPicker' not found. The requested module 'vue3-colorpicker' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'vue3-colorpicker';
const { ColorPicker } = pkg;

**Comment by why-try313** [comment]
CommonJS is a NodeJS module system, while I agree it's not the best scenario ES6 can still be used as a solution
Please see [Do's and dont's of the "Importing modules" section](https://github.com/why-try313/godot-ECMAScript-cookbook/wiki/3.5-%E2%80%90-05-Importing-modules#dos-and-donts)
