### ISSUE TITLE
Not possible to manipulate x or y of built-in vectors

### ISSUE THREAD

**Issue by drusin** [Geequlim/ECMAScript#17]
Create something with a `Position`, like `Area2D`. Now try to manipulate only `x` or only `y` of the position:

```JavaScript
export default class Player extends godot.Area2D {
    constructor() {
        this.velocity = new godot.Vector2();
    }
    _process() {
        this.velocity.x++; //this works!
        this.position.x++; //this should work but doesn't!
        this.position = new godot.Vector2(this.position.x + 1, this.position.y); //this works!
    }
}
```
I tried with `position` and `scale`, I assume all built-in vecors might behave the same.

**Comment by Geequlim** [comment]
You have to assign to the position property as all builtin types are value-like.

**Comment by Geequlim** [comment]
this.position += new godot.Vector2(1,0)

**Comment by drusin** [comment]
Stuff like `position.x = clamp(position.x, 0, screen_size.x)` works in *.gd, so I assumed it sould also work in *.js

**Comment by Geequlim** [comment]
Does it works in C# ?

**Comment by drusin** [comment]
No, it doesn't. So probably intended?
