### ISSUE TITLE
[4.1-v0.0.17] Signal arguments makes it crash

### ISSUE THREAD

**Issue by why-try313** [Geequlim/ECMAScript#175]
#### Concerned version
[4.1-v0.0.17-alpha-20231003](https://github.com/Geequlim/ECMAScript/actions/runs/6473613422)

#### Problem
It seems that any function passing arguments makes the application crash, both on editor connection and using the `.connect(str, fn)` method

#### What works:
- Connect a signal via editor as long the signal doesn't return arguments (0 args)
- Connect a signal via code as long the signal doesn't return arguments (0 args)
- Connect a signal via code and pass an anonymous function to trigger the method with an argument  <br> `this.connect("sig_name", () => { this.myMethod(myValueHere) })` 

#### What doesn't work:
- Connect a signal via editor that passes at least one argument (full freeze)
- Connect a signal via code that returns arguments (full freeze) <br> `this.connect("input_event", this.myMethod) // returns 5 arguments` 
- Connect a signal via code that passes at least one argument as third parameter (argument ignored) <br> `this.connect("sig_name", this.myMethod, [myValue])`
- Connect a signal via code that passes at least one argument [with bind](https://docs.godotengine.org/en/stable/classes/class_signal.html#class-signal-method-connect)  (argument ignored) <br> `this.connect("sig_name", this.myMethod.bind(myValue))`

#### Observations
1) It seems that after re-establishing [binding_script.js](https://github.com/Geequlim/ECMAScript/blob/master/misc/binding_script.js) with some modifications the connect method in code passes the arguments array<br>
``` JS
// From
return godot_object_connect.apply(this, [signal, target, method_name, params, flags]);
// To
return godot_object_connect.apply(this, [signal, target[method_name], params, flags]);
/// Apply this to all Object.defineProperty return statements
```
2) Connecting a method on the editor doesn't match the number of arguments since `MethodInfo` doesn't set the number of arguments in [/quickjs/quickjs_binder.cpp:L1871](https://github.com/Geequlim/ECMAScript/blob/master/thirdparty/quickjs/quickjs_binder.cpp#L1871)
![connect issued](https://github.com/Geequlim/ECMAScript/assets/18019207/20b5149f-a877-4a64-a6d4-e26b7bcf4664)

***Note :*** The parameters seem to be received by the functions since they are logged on the terminal that runs godot but freezes the program completly after printing them

**Comment by fire** [comment]
Maybe we are not passing the arguments correctly with 0 count.

**Comment by fire** [comment]
I wonder if it's Camera3D access that's crashing?

**Comment by nmerget** [comment]
> Another problem that might be Signal related, TextEdit completly ignores keyboard inputs or clicks

If you add a script on a `TextEdit` it stops working...
If you place the script on a `Control` above and trigger the signal from `TextEdit` to the `Control` it isn't ignoring the clicks

**Comment by nmerget** [comment]
> TextEdit

Moved this to https://github.com/Geequlim/ECMAScript/issues/206
