### ISSUE TITLE
Get started page 404

### ISSUE THREAD

**Issue by Hadaward** [Geequlim/ECMAScript#176]
Clicking on getting started or documentation takes us to a page that doesn't exist, the 404 error appears

https://geequlim.github.io/ecmascript/getting-started

**Comment by why-try313** [comment]
Some context: [README.md](https://github.com/Geequlim/ECMAScript#documentation-tutorials--demos) documentation link is lowercased, since the router of the website is case sensitive it breaks the link
**Note:** this should be renamed README.md documentation link is broken

**Comment by fire** [comment]
Seems fixed?
