### ISSUE TITLE
Missing template / examples for pre-release

### ISSUE THREAD

**Issue by rmgaray** [Geequlim/ECMAScript#179]
Hello! As a newcomer, I am having some issues trying out this project in its pre-release state. There are templates and examples for Godot 3.5, but this is unfortunately of no use to me, as I need to use Godot 4.X .

When testing the projects at [ECMAScriptDemos](https://github.com/geequlim-godot-related/ECMAScriptDemos), none of the Javascript implemented classes seem to work (e.g: the sprite in the `npm_module` example does not spin). Of course, these projects were written for Godot 3.5 and needed to be converted to 4.X, so I don't expect them to work without some work in updating them.

Could perhaps the developers of this project kindly provide an example project using the latest pre-release of ECMAScript? Or maybe some instruction on how to set up such an example? I can provide more information if necessary about the issues I found when trying the ECMAScript demos.

**Comment by fukaraadam** [comment]
Created a simple template for 4.x to show npm module usage. Hope it would be helpful for now: https://github.com/Cumulativerse/godot-js-template

**Comment by rmgaray** [comment]
Thank you @fukaraadam! I will happily study your template.

**Comment by nmerget** [comment]
The template is mentioned in the [README.md](https://github.com/Geequlim/ECMAScript/blob/master/README.md?plain=1#L49). I will close this :)
