### ISSUE TITLE
Condition "!is_inside_tree()" is true.

### ISSUE THREAD

**Issue by fukaraadam** [Geequlim/ECMAScript#184]
ECMAScript Release: 4.1-v0.0.17-alpha-20231003
Current OS: Windows 10 x64

1- When I download and launch Godot, as default there are error messages in every project (even if created new projects):

`scene\gui\control.cpp:1999 - Condition "!is_inside_tree()" is true.`

![image](https://github.com/Geequlim/ECMAScript/assets/24752545/b033de22-19a9-44e7-8e18-1505b96cefae)

2- Furthermore, when I add simple mjs class, I had to edit and save it through Godot Editor. If Iast save made by any other editor like notepad++ or VSCode (even if created script through Godot and not edited in Godot Editor), it produces following errors:

`Cannot load script in this thread`
`Parse source code from file 'res://js/demo.mjs' failed.`
`Failed loading resource: res://js/demo.mjs. Make sure resources have been imported by opening the project in the editor at least once.`

![image](https://github.com/Geequlim/ECMAScript/assets/24752545/3d51656e-c84d-41f3-9742-ed17281cf3c6)

![image](https://github.com/Geequlim/ECMAScript/assets/24752545/56c34684-a32c-4f59-a51f-9c62463862c5)

I am not sure if second problem related to first problem, but it is especially problematic if using builder scripts like esbuild, since they produce files automatically. For second problem I have found this:

- javascript.cpp reload() function calls get_thread_binder() function from some arbitrary thread (p_id) if mjs script not edited by Godot Editor. 
- thread_binder_map only have main thread inside it, since thread_binder_map.getptr(p_id) returns null.

![image](https://github.com/Geequlim/ECMAScript/assets/24752545/ec1248e7-ff4d-477a-ac03-1da206f6a5b2)

![image](https://github.com/Geequlim/ECMAScript/assets/24752545/2af66791-c093-464c-b6c3-e5eb33802ed8)

**Comment by nmerget** [comment]
I saw these issues in the last version as well. And to be honest TS and esbuild are the way to go. 
It's hard for me to fix such issues because I'm not a C++ Developer. I'll try my best to look for a solution.

**Comment by nmerget** [comment]
I fixed the second issue by adding additional checks: 
https://github.com/Geequlim/ECMAScript/pull/189
