### ISSUE TITLE
Master build does not build with Godot

### ISSUE THREAD

**Issue by Reiss-Cashmore** [Geequlim/ECMAScript#185]
Hi,

I followed the steps in the README. Cloned master of Godot engine, cloned the ECMAScript into modules directory. 

Ran: `scons platform=macos arch=arm64 warnings=extra werror=yes module_text_server_fb_enabled=yes`

Get the following error. I'm using all the recommended versions based on the Godot documentation Python 3.6, SCons: v4.6.0

```
[Initial build] Compiling modules/javascript/thirdparty/quickjs/quickjs_callable.cpp ...
[Initial build] Compiling modules/javascript/thirdparty/quickjs/quickjs_debugger.cpp ...
In file included from modules/javascript/thirdparty/quickjs/quickjs_binder.cpp:14:
[Initial build] error: 'notification' marked 'override' but does not override any member functions
        /* TODO */ virtual void notification(int p_notification) override{};
                                ^
[Initial build] Compiling modules/javascript/thirdparty/quickjs/quickjs_worker.cpp ...
[Initial build] Compiling modules/javascript/thirdparty/quickjs/quickjs/cutils.c ...
1 error generated.
scons: *** [modules/javascript/thirdparty/quickjs/quickjs_binder.macos.editor.arm64.o] Error 1
scons: building terminated because of errors.
[Time elapsed: 00:00:51.058]
```

**Comment by nmerget** [comment]
The problem here is that some `APIs` in godot change between versions.
The current `master` of this repo was build with `4.1` and the `master` of the [godot](https://github.com/godotengine/godot/blob/master/version.py#L4) is `4.3`.

This should be documented in the Readme to use the correct version.

**Comment by Reiss-Cashmore** [comment]
> The problem here is that some `APIs` in godot change between versions. The current `master` of this repo was build with `4.1` and the `master` of the [godot](https://github.com/godotengine/godot/blob/master/version.py?rgh-link-date=2024-01-18T15%3A34%3A04Z#L4) is `4.3`.
> 
> This should be documented in the Readme to use the correct version.

Thanks for the reply and clarity
