### ISSUE TITLE
Unicode parsing error: Invalid unicode codepoint (fffd), cannot represent as ASCII/Latin-1

### ISSUE THREAD

**Issue by alexeychikk** [Geequlim/ECMAScript#186]
Im following the official Squash the Creeps godot tutorial but using TypeScript.
In the Godot Engine I see the following error:
```
  Unicode parsing error: Invalid unicode codepoint (fffd), cannot represent as ASCII/Latin-1
```
Here is my repo where this is reproducible:
https://github.com/alexeychikk/ts-godot-squash-the-creeps

You'll need to:
```shell
npm i
npm run ts
```

**Comment by nmerget** [comment]
I got the same issue in my test repo. I found [this](https://github.com/godotengine/godot/issues/61756).
Maybe it is just an issue from using the wrong [String](https://github.com/godotengine/godot/issues/61756#issuecomment-1175818459) somewhere
