### ISSUE TITLE
How do you export a PackedScene?

### ISSUE THREAD

**Issue by drusin** [Geequlim/ECMAScript#19]
I'm trying to redo https://docs.godotengine.org/en/latest/getting_started/step_by_step/your_first_game.html#main-scene with ECMAScript and did not manage to translate `export (PackedScene) var Mob`.
I tried
```Javascript
import Mob from 'res://mob.js';
godot.register_property(Main, 'Mob', Mob);
```
and
```JavaScript
godot.register_property(Main, 'Mob', godot.PackedScene);
```
but both crashed the editor. What's the correct way to do this?

**Comment by drusin** [comment]
There is no console error message at all when the editor crashes in the dirst example.

`godot.register_property(Main, 'Mob', godot.PackedScene);` produces
```
ERROR: object_method: Parameter "bind" is null.
   At: modules/ECMAScript/quickjs/quickjs_binder.cpp:77
```
a few hundred times before crashing.

**Comment by Geequlim** [comment]
The third paramater is **default value**. You don't need to tell the api type, the type will be detected automaticly.

Try this
```js
godot.register_property(Main, 'Mob', new godot.PackedScene());
```

**Comment by drusin** [comment]
this works, thanks a lot!
