### ISSUE TITLE
Porting for multiplatform

### ISSUE THREAD

**Issue by Geequlim** [Geequlim/ECMAScript#2]
## Linux
   - [x] GCC  x64 debug
   - [x] GCC  x64 release
   - [ ] Clang x64 debug
   - [ ] Clang x64 release

## Windows
   - [x] MSVC x64 debug
   - [x] MSVC x64 release
   - [ ] MSVC x86 debug
   - [ ] MSVC x86 debug

## OSX
  - [x] Clang x64 debug
  - [ ] Clang x64 release

**Comment by Geequlim** [comment]
@arimus Could you please test compiling for OSX and feedback here ?

**Comment by arimus** [comment]
@Geequlim carrying on the conversation from https://github.com/godotengine/godot/issues/937 over here. I'm using ECMAScriptDemos/* projects to test. Godot locks up completely and I have to kill it.

**Comment by arimus** [comment]
Here's the error message trying to run hello_world:

**Comment by Geequlim** [comment]
@arimus Did you compiled typescript before you run the project?

**Comment by arimus** [comment]
Yes. In both the pong and hello world projects. The odd pay is that the
first time I opened the hello world project, I got that one too work. But
then I couldn't get it to open again... Even after resetting the project
changes.

**Comment by arimus** [comment]
@Geequlim Any guidance on how I can get past these errors. Updated to the latest, but still having the exact same errors.

**Comment by Geequlim** [comment]
@arimus Sorry I don't have a Mac to test yet. And other people test on OSX is fine.

**Comment by Geequlim** [comment]
@arimus Did you try the demos without editor? IMO the ecmascript module should never crash the godot editor.

**Comment by arimus** [comment]
I am indeed able to run hello world and pong without the editor. The editor is what worked for me initially and I have not been able to reproduce.

1. Clone of godot (master)
2. Clone of ECMAScript
3. Copy ECMAScript into godot/modules
4. scons platform=osx
5. Clone of ECMAScriptDemos
6. Follow directions in project to build
7. Run with editor ../../godot/bin/godot.osx.tools.64 project.godot (does not work)
8. Run without editor ../../godot/bin/godot.osx.tools.64 Main.tscn (works)

I can open another complex project with this build new build of Godot just fine and run it in the editor btw. Also, I can change the Pong project version and open it in Godot 2. It doesn't do anything but show the main board, but it doesn't hang like the new build does for me.

Let me know if there is anything else I can help with for editor support.

Other details:
```
$ clang --version
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by Geequlim** [comment]
@arimus  Try remove project cache of your projects ?
On Windows it is here.
![image](https://user-images.githubusercontent.com/6964556/54106998-d844d300-4412-11e9-9c54-69bc985ea1a1.png)

**Comment by Geequlim** [comment]
@arimus  I don't know is it related. On OSX you need to put the compiled binary file into `godot.app` .

**Comment by arimus** [comment]
I tried to clear the caches in ~/.godot and removed the .import directory from the Pong project and tried to edit. It still dies on import. I modified the project to see which file was loading when errors crop up. Here is what I get in the console:

```
Loading file res://bin/bundle.js
ERROR: safe_eval_text: Condition ' Thread::get_caller_id() != Thread::get_main_id() ' is true. returned: ERR_UNAVAILABLE
   At: modules/ECMAScript/duktape/duktape_binding_helper.cpp:188.
ERROR: load: Condition ' err != OK ' is true. returned: RES()
   At: modules/ECMAScript/ecmascript_library.cpp:27.
ERROR: _load: Failed loading resource: res://bin/bundle.js
   At: core/io/resource_loader.cpp:285.
Loading file res://bin/bundle.js
ERROR: safe_eval_text: Condition ' Thread::get_caller_id() != Thread::get_main_id() ' is true. returned: ERR_UNAVAILABLE
   At: modules/ECMAScript/duktape/duktape_binding_helper.cpp:188.
ERROR: load: Condition ' err != OK ' is true. returned: RES()
   At: modules/ECMAScript/ecmascript_library.cpp:27.
ERROR: _load: Failed loading resource: res://bin/bundle.js
   At: core/io/resource_loader.cpp:285.
WARNING: _parse_ext_resource: Couldn't load external resource: res://bin/bundle.js
   At: scene/resources/resource_format_text.cpp:175.
```

Re: bundling in godot.app, I tried just in case the plist made a difference, but it did not. From what I can tell in the docs, it's unnecessary anyways.
