### ISSUE TITLE
4 Questions in a Single Picture.

### ISSUE THREAD

**Issue by BracerJack** [Geequlim/ECMAScript#26]
https://i.imgur.com/MJ5uiQS.png

Thank you for working towards giving Godot the ease of use of JavaScript.

**Comment by Yaft** [comment]
Reading from the image was inconvenient. As far as I understand, there is a misunderstanding of the work of "Class syntax"

https://javascript.info/class

**Comment by Geequlim** [comment]
Sorroy I can't open the image behand the Great Fire Wall.

**Comment by BracerJack** [comment]
> 
> 
> Reading from the image was inconvenient. As far as I understand, there is a misunderstanding of the work of "Class syntax"
> 
> https://javascript.info/class

Thank you !
Do you happen to know why the for loop and setInterval doesn't work ?

**Comment by Yaft** [comment]
> > Reading from the image was inconvenient. As far as I understand, there is a misunderstanding of the work of "Class syntax"
> > https://javascript.info/class
> 
> Thank you !
> Do you happen to know why the for loop and setInterval doesn't work ?

`print is not defined` use `console.log(counter)`

`setInterval is not defined` setInterval не реализован в данном api, но даже если бы он был реализован, то доступ к методу необходимо было бы осуществлять через контекст класса `setInterval(this.testing, 1000);`

```js
export default class test extends godot.Node2D {
	
	// Declare member variables here. Examples:
	a = 2;
	b = "text";
	
	constructor() {
		super();
	}

	testing() {
		console.log("test");
	}

	// Called when the node enters the scene tree for the first time.
	_ready() {
		for (let i = 0; i < 100; i += 1) {
			console.log(i);
		}
		
		this.testing()
	}
	// Called every frame. 'delta' is the elapsed time since the previous frame.
	_process(delta) {
		
	}
}
```

**Comment by BracerJack** [comment]
Thank you Yaft, you are wonderful :D

**Comment by Yaft** [comment]
> 
> 
> Thank you Yaft, you are wonderful :D
> Without setInterval...I wonder how would one set up a timer.

[Godot API Timer](https://docs.godotengine.org/en/stable/classes/class_timer.html#class-timer-set-wait-time)
