### ISSUE TITLE
console.log(godot.Performance.get_monitor(Performance.TIME_FPS));

### ISSUE THREAD

**Issue by BracerJack** [Geequlim/ECMAScript#27]
console.log(godot.Performance.get_monitor(Performance.TIME_FPS));

Error "Performance not defined".

I also tried: console.log(Performance.get_monitor(Performance.TIME_FPS));

Both doesn't work.

**Comment by Geequlim** [comment]
console.log(godot.Performance.get_monitor(godot.Performance.TIME_FPS));

**Comment by BracerJack** [comment]
Thank you  Geequlim !
