### ISSUE TITLE
Suggested improvements to async workflow

### ISSUE THREAD

**Issue by nhydock** [Geequlim/ECMAScript#5]
With Javascript being very async heavy, and ECMAScript not having to completely match how GDScript implements its features, there's potentially to provide slight usability improvements to the workflow with regards to Godot coroutines and signals workflow.  These do not need to be implemented at a low level and may just be shims that wrap existing behavior 

- Support async/await against GDScript yielded functions

```
#gdscript Player
func jump():
  var anim = $AnimationPlayer
  anim.play("jump")
  yield($AnimationPlayer, "animation_finished")

// javascript
async function() {
  const player = get_node("Player");
  const result = await player.jump();
}
```

- Support for closures or literal function references in place of Godot funcref/method-name binding functions

```
node.connect("my_signal", (param) => { console.log(param) });
node.connect("my_signal", this.mySignalHandler);
```

- Convenience method to wrap one-shot signal connections in Promises

```
// with async/await
const async_result = await godot.OnSignal(node, "my_signal")
do_stuff(async_result);

// or with promises
godot.OnSignal(node, "my_signal")
  .then((result) => { do_stuff(result) })
```
If developers want to have a more advance version of the signalling, they could write a custom wrapper using RxJS where results get piped into an Observable.

**Comment by Geequlim** [comment]
> Support for closures or literal function references in place of Godot funcref/method-name binding functions

This is implemented now

```js
const MY_SIGNAL = "test_signal";
function global_function(...args) {
	console.log('global_function:', this, ...args); // <== check this is the one we bind when connect
}

export default class MyNode extends godot.Node2D {
	
	_ready() {
		console.log(this);
		this.connect(MY_SIGNAL, this, 'tradition_slot', ['from taditional connection']);
		this.connect(MY_SIGNAL, this, this.method, ['from method of object']);
		this.connect(MY_SIGNAL, this, function(...args){
				console.log('Anonymous method:', this, ...args); // <== check this value
			},
			["from lambda function"]
		);
		this.connect(MY_SIGNAL, this, global_function, ["from global function"]);
		// emit the signal with parameter 'Wow'
		this.emit_signal(MY_SIGNAL, 'Wow');
	}
	
	tradition_slot(...args) {
		console.log("MyNode.tradition_slot:", this, ...args)
	}
	
	method(...args) {
		console.log("MyNode.method:", this, ...args)
	}
}
godot.register_signal(MyNode, MY_SIGNAL);
```

Output
```
[Node2D:1187]
MyNode.method: [Node2D:1187] Wow from method of object
Anonymous method: [Node2D:1187] Wow from lambda function
MyNode.tradition_slot: [Node2D:1187] Wow from taditional connection
global_function: [Node2D:1187] Wow from global function
```

**Comment by Geequlim** [comment]
These features are implemented now.
![carbon (2)](https://user-images.githubusercontent.com/6964556/70391525-2e31c000-1a11-11ea-8648-01b44d53fb4f.png)
![carbon (3)](https://user-images.githubusercontent.com/6964556/70391519-25d98500-1a11-11ea-9fc5-fa3785789881.png)

**Comment by nhydock** [comment]
Instead of passing in null as the target, could the param be made optional for anonymous functions?

Also godot.yield would benefit from having a default value of `'completed'` be assigned to the signal parameter since it's the most common use-case to yield for.

**Comment by Geequlim** [comment]
Thanks for your advice. These features are implemented now.
