### ISSUE TITLE
exporting does not work

### ISSUE THREAD

**Issue by fidasx** [Geequlim/ECMAScript#6]
im getting this error:

```
ERROR: _load: No loader found for resource: res://Main.js.
At: core/io/resource_loader.cpp:280.
ERROR: poll: res://Main.tscn:3 - Parse Error: [ext_resource] referenced nonexistent resource at: res://Main.js
At: scene/resources/resource_format_text.cpp:440.
ERROR: load: Failed to load resource 'res://Main.tscn'.
At: core/io/resource_loader.cpp:208.
ERROR: _load: Failed loading resource: res://Main.tscn.
At: core/io/resource_loader.cpp:278.
ERROR: start: Failed loading scene: res://Main.tscn
At: main/main.cpp:1846.
WARNING: cleanup: ObjectDB Instances still exist!
At: core/object.cpp:2074.
ERROR: clear: Resources Still in use at Exit!
At: core/resource.cpp:473.
```

it works fine running from the editor 
btw what export templates do i have to use with your builds
thx for your time developing this

**Comment by Geequlim** [comment]
export is not implemented yet

**Comment by Geequlim** [comment]
The plan to implement exporting ECMAScript is to compile scripts to byte code.

@fidasx You can using the editor itself as the export template binary before the exporting feature is implemented.

**Comment by fidasx** [comment]
ok ty very much

**Comment by Geequlim** [comment]
ECMAScript exporting is implemented now.
We can export script with encryption key or compile to bytecode
