### ISSUE TITLE
Cannot attach node script

### ISSUE THREAD

**Issue by gforceg** [Geequlim/ECMAScript#7]
I am trying to use this in godot (tagged commit 3.1.2-stable) with ECMAScript (tagged commit godot3.1-duktape) and the Godot UI will not allow me to attach an ECMAScript to a Node2D. It seems like a form validation issue but maybe I'm doing something wrong?

![image](https://user-images.githubusercontent.com/14267747/73155415-e980e780-4097-11ea-8915-f513bafaa02e.png)

I've tried using the alpha3 branch as well but that one won't build w/ godot 3.1.2-stable. I'm going to try more branches, but do you know what the issue might be?

**Comment by gforceg** [comment]
I created the file outside of Godot and things seem to be working now.

**Comment by gforceg** [comment]
I guess I spoke too soon, now it reloads the same dialog over and over.

**Comment by Geequlim** [comment]
The duktape is replaced by quickjs. You'd better try the latest version

**Comment by gforceg** [comment]
Thanks for your reply @Geequlim,

I will try that.

I initially tried using alpha3 w/ godot@3.1.2-stable and the godot build kept failing.

**Comment by gforceg** [comment]
Works with both master branches.
Thanks! :stuck_out_tongue_winking_eye:
