### ISSUE TITLE
is it possible to import es5 / es6 modules?

### ISSUE THREAD

**Issue by gforceg** [Geequlim/ECMAScript#8]
I tried to import typescript / javascript modules but it doesn't seem to like the module format I'm using.

godot generates an error:

```
E 0:00:00.514   reload: JavaScript Error    at <anonymous> (res://node_modules/of-range/range.js:2)
exports is not defined
  <C++ Source>  modules/ECMAScript/ecmascript.cpp:90 @ reload()
```

I have tried both node_modules and and files within my project directory. I think a way around this problem would be to use a bundler such-as webpack but I am hoping there is a simpler way to make this work.

**Comment by Geequlim** [comment]
You can only using  standard ES6 modules format.

**Comment by gforceg** [comment]
Thanks! I thought I had tried ES6 but I was wrong. It's working now.
